"""Manchester Airport (MAN) destinations — April 2026."""

DESTINATIONS = {
    "MAN": {
        "name": "Manchester",
        "routes": {
            "ABZ": "Aberdeen",
            "ACE": "Lanzarote",
            "ADB": "Izmir",
            "ADD": "Addis Ababa",
            "AEY": "Akureyri",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ANU": "Antigua",
            "ARN": "Stockholm",
            "ATH": "Athens",
            "AUH": "Abu Dhabi",
            "AYT": "Antalya",
            "BAH": "Bahrain",
            "BCN": "Barcelona",
            "BDS": "Brindisi",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGI": "Barbados",
            "BGO": "Bergen",
            "BGY": "Milan Bergamo",
            "BHD": "Belfast City",
            "BIO": "Bilbao",
            "BJL": "Banjul",
            "BJV": "Bodrum",
            "BLQ": "Bologna",
            "BOD": "Bordeaux",
            "BOJ": "Bourgas",
            "BOM": "Mumbai",
            "BRS": "Bristol",
            "BSL": "Basel",
            "BTS": "Bratislava",
            "BUD": "Budapest",
            "BVA": "Paris Beauvais",
            "BVC": "Boa Vista",
            "BZR": "Beziers",
            "CAI": "Cairo",
            "CCF": "Carcassonne",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CGN": "Cologne Bonn",
            "CHQ": "Chania",
            "CMF": "Chambery",
            "CMN": "Casablanca",
            "CPH": "Copenhagen",
            "CRL": "Brussels Charleroi",
            "CTA": "Catania",
            "CUN": "Cancun",
            "DAC": "Dhaka",
            "DEL": "Delhi",
            "DJE": "Djerba",
            "DLM": "Dalaman",
            "DOH": "Doha",
            "DUB": "Dublin",
            "DUS": "Dusseldorf",
            "DXB": "Dubai",
            "EIN": "Eindhoven",
            "ENF": "Enontekio",
            "EXT": "Exeter",
            "FAO": "Faro",
            "FCO": "Rome",
            "FMM": "Memmingen",
            "FNC": "Funchal",
            "FRA": "Frankfurt",
            "FUE": "Fuerteventura",
            "GCI": "Guernsey",
            "GDN": "Gdansk",
            "GIB": "Gibraltar",
            "GOA": "Genoa",
            "GOI": "Goa",
            "GOT": "Gothenburg",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HAM": "Hamburg",
            "HEL": "Helsinki",
            "HER": "Heraklion",
            "HKG": "Hong Kong",
            "HKT": "Phuket",
            "HRG": "Hurghada",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "ISB": "Islamabad",
            "IST": "Istanbul",
            "JED": "Jeddah",
            "JER": "Jersey",
            "JFK": "New York JFK",
            "JMK": "Mykonos",
            "JSI": "Skiathos",
            "JTR": "Santorini",
            "KAO": "Kuusamo",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KIR": "Kerry",
            "KLX": "Kalamata",
            "KOI": "Kirkwall",
            "KRK": "Krakow",
            "KTT": "Kittila",
            "KTW": "Katowice",
            "KUN": "Kaunas",
            "KVA": "Kavala",
            "KWI": "Kuwait",
            "LAS": "Las Vegas",
            "LCA": "Larnaca",
            "LDY": "Derry",
            "LEI": "Almeria",
            "LGW": "London Gatwick",
            "LHR": "London Heathrow",
            "LIG": "Limoges",
            "LPA": "Gran Canaria",
            "LRH": "La Rochelle",
            "LRM": "La Romana",
            "LUX": "Luxembourg",
            "LXR": "Luxor",
            "LYS": "Lyon",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MBJ": "Montego Bay",
            "MCO": "Orlando",
            "MJT": "Lesvos",
            "MLA": "Malta",
            "MRS": "Marseille",
            "MUC": "Munich",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NOC": "Knock",
            "NQY": "Newquay",
            "NTE": "Nantes",
            "OHD": "Ohrid",
            "OLB": "Olbia",
            "OPO": "Porto",
            "ORK": "Cork",
            "OSL": "Oslo",
            "OTP": "Bucharest",
            "PDV": "Plovdiv",
            "PEK": "Beijing",
            "PFO": "Paphos",
            "PMI": "Palma",
            "PRG": "Prague",
            "PUJ": "Punta Cana",
            "PUY": "Pula",
            "PVG": "Shanghai",
            "PVK": "Preveza",
            "RAK": "Marrakesh",
            "RBA": "Rabat",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RIX": "Riga",
            "RMU": "Murcia",
            "RNS": "Rennes",
            "RVN": "Rovaniemi",
            "RZE": "Rzeszow",
            "SDR": "Santander",
            "SID": "Sal",
            "SIN": "Singapore",
            "SKG": "Thessaloniki",
            "SNN": "Shannon",
            "SOF": "Sofia",
            "SOU": "Southampton",
            "SPC": "La Palma",
            "SPU": "Split",
            "SSH": "Sharm El Sheikh",
            "STN": "London Stansted",
            "STR": "Stuttgart",
            "SUF": "Lamezia Terme",
            "SVG": "Stavanger",
            "SVQ": "Seville",
            "SZG": "Salzburg",
            "TFS": "Tenerife South",
            "TIA": "Tirana",
            "TIV": "Tivat",
            "TLS": "Toulouse",
            "TNG": "Tangier",
            "TOS": "Tromso",
            "TPS": "Trapani",
            "TRN": "Turin",
            "VCE": "Venice",
            "VIE": "Vienna",
            "VLC": "Valencia",
            "VRN": "Verona",
            "WAW": "Warsaw",
            "WRO": "Wroclaw",
            "XRY": "Jerez",
            "YYZ": "Toronto",
            "ZAD": "Zadar",
            "ZAG": "Zagreb",
            "ZRH": "Zurich",
            "ZTH": "Zakynthos",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
